### ISSUE TITLE
Uncaught runtime errors

### ISSUE THREAD

**Issue by meetgyn** [dev-lu/osint_toolkit#34]
Help Please

![image](https://github.com/dev-lu/osint_toolkit/assets/3695608/52593fdf-33af-4708-9b93-9c49759f33ce)
![image](https://github.com/dev-lu/osint_toolkit/assets/3695608/d58ccd01-7491-4a91-a9c9-8860d9b6999c)

**Comment by dev-lu** [comment]
Hello meetgyn,

The issue was caused by an error when using newer versions of Python with an older version of Pydantic. I've updated the requirements, so it should work now. Please clone the latest version of the repository and run `docker compose build` to rebuild the image.

Additionally, your compose file needs some adjustments. Based on your configuration, it should look like this:
```yaml
version: "3.8"
services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8010:8000"
    volumes:
      - ./data:/backend/database/data
  frontend:
    build:
      context: ./frontend
      args:
        BACKEND_URL: http://localhost:8010  # Backend URL without trailing slash
    container_name: frontend
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
```

**Comment by meetgyn** [comment]
Thank you very much. I will make a new attempt.

**Comment by meetgyn** [comment]
![image](https://github.com/dev-lu/osint_toolkit/assets/3695608/ce69e786-27be-427f-9dad-768ccfe16b3a)

**Comment by dev-lu** [comment]
It seems like your Docker host or installation is not able to connect to the internet to install the dependencies. Please check your network configuration to fix this error.

**Comment by meetgyn** [comment]
Hello, my friend. So, I did some new tests here, and indeed, this problem persists. I have four more Docker containers running without any issues, so I believe it's neither a network problem with Docker nor with the host. But thanks for your help. I am giving up on this.
